server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: cloud-gateway_pay_route1
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/get/**
#            - Header=X-Request-Id, \d+
            - My=diamond
#            - name: My
#              args:
#                userType: diamond
        - id: cloud-gateway_pay_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**
        - id: cloud-gateway_pay_route3
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/circuit/**
        - id: cloud-gateway_pay_route4
          uri: lb://cloud-payment-service
          predicates:
#            - Path=/pay/gateway/filter/**
#            - Path=/gateway/filter/**
            - Path=/XYZ/abc/{param}
          filters:
            - My=frank
            - AddRequestHeader=X-Request-frank1,frankValue1
#            - AddRequestHeader=X-Request-frank2,frankValue2
#            - RemoveRequestHeader=sec-fetch-site
#            - SetRequestHeader=sec-fetch-mode,Blue-updatefrank
#            - AddRequestParameter=customerName
#            - AddResponseHeader=X-Response-frank,BlueResponse
#            - SetResponseHeader=Date,2099-01-01
#            - RemoveResponseHeader=Content-Type
#            - PrefixPath=/pay
            - SetPath=/pay/gateway/{param}
#            - RedirectTo=302, http://www.google.com
