server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    consul:
      host: localhost # default
      port: 8500 # default
      discovery:
        service-name: ${spring.application.name}