spring:
  application:
    name: spring_kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 2
      enable-auto-commit: true
      auto-offset-reset: earliest
      auto-commit-interval: 1s
    properties:
      session.timeout.ms: 120000
      max.poll.interval.ms: 300000
      request.timeout.ms: 600000
      allow.auto.create.topics: true
      heartbeat.interval.ms: 40000
    template:
      default-topic: "test"


# kafka publish config
kafka:
  pub:
    deviceId: 100081
    deviceName: k_o_p-o-p
    measurePoint: ONOFF
    siteId: shawn
