server:
  port: 80

spring:
  application:
    name: cloud-order-service
  datasource:
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: password
  cloud:
    consul:
      host: localhost # default
      port: 8500 # default
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
    openfeign:
      client:
        config:
          #          default:
          #            connect-timeout: 3000
          #            read-timeout: 3000
          # specific service config
          cloud-payment-service:
            connect-timeout: 20000
            read-timeout: 20000
      httpclient:
        hc5:
          enabled: true
      compression:
        request:
          enabled: true
          mime-types: text/xml, application/xml, application/json
          min-request-size: 2048
        response:
          enabled: true
      circuitbreaker:
        enabled: true
#        group:
#          enabled: true

resilience4j:
  # circuit breaker
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        sliding-window-type: COUNT_BASED
        sliding-window-size: 6
        minimum-number-of-calls: 6
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        record-exceptions:
          - java.lang.Exception
    instances:
      cloud-payment-service:
        base-config: default
  # bulkhead (semaphore)
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 2
        max-wait-duration: 1s
    instances:
      cloud-payment-service:
        base-config: default
  # bulkhead (fixed threadPool)
  thread-pool-bulkhead:
    configs:
      default:
        # max + queue -> max concurrent no of thread = 2
        core-thread-pool-size: 1
        max-thread-pool-size: 1
        queue-capacity: 1
    instances:
      cloud-payment-service:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 20s # default 1s
  ratelimiter:
    configs:
      default:
        limit-for-period: 2
        limit-refresh-period: 1s
        timeout-duration: 1s
    instances:
      cloud-payment-service:
        base-config: default
#logging:
#  level:
#    org:
#      frank:
#        cloud:
#          apis:
#            PayFeignApi: debug
# ========================zipkin========================
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 # default 0.1