server:
  port: 80

spring:
  application:
    name: cloud-order-service
  datasource:
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: password
  cloud:
    consul:
      host: localhost # default
      port: 8500 # default
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 3000
          # specific service config
          cloud-payment-service:
            connect-timeout: 4000
            read-timeout: 4000